version: "3"
services:
  livestream:
    image: ghcr.io/sb-im/charoite:debug-livestream
    container_name: livestream
    command:
      - --debug
      - --profile
      - livestream
      - -c
      - /etc/charoite/config.toml
    ports:
      - "5004:5004/udp"
      - "5005:5005/udp"
      - "1935:1935"
      - "127.0.0.1:16060:6060"
    volumes:
      - ./config/config.edge.toml:/etc/charoite/config.toml:ro
    depends_on:
      - mosquitto
      - broadcast
      - turn
      - loki
    restart: always
    logging: &loki
      driver: loki
      options:
        loki-url: "http://localhost:3100/api/prom/push"

  broadcast:
    image: ghcr.io/sb-im/charoite:debug-broadcast
    container_name: broadcast
    command:
      - --debug
      - --profile
      - broadcast
      - -c
      - /etc/charoite/config.toml
    ports:
      - "8080:8080"
      - "127.0.0.1:16061:6060"
    volumes:
      - ./config/config.cloud.toml:/etc/charoite/config.toml:ro
    depends_on:
      - mosquitto
      - turn
      - loki
    restart: always
    logging: *loki

  turn:
    image: ghcr.io/sb-im/charoite:debug-turn
    container_name: turn
    command:
      - --debug
      - turn
      - -c
      - /etc/charoite/config.toml
    volumes:
      - ./config/config.cloud.toml:/etc/charoite/config.toml:ro
    depends_on:
      - loki
    restart: always
    logging: *loki

  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    depends_on:
      - loki
    restart: always
    logging: *loki

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    restart: always
    logging: *loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: always
    logging: *loki
