FROM golang:1.16-buster

# See: https://docs.github.com/en/packages/guides/connecting-a-repository-to-a-container-image#connecting-a-repository-to-a-container-image-on-the-command-line
LABEL org.opencontainers.image.source=https://github.com/SB-IM/sphinx

WORKDIR /src

COPY go.mod .

# See: https://docs.docker.com/develop/develop-images/build_enhancements/
# http://blog.oddbit.com/post/2019-02-24-docker-build-learns-about-secr/
RUN --mount=type=ssh,id=github git config --global url."git@github.com:".insteadOf "https://github.com/"; \
    mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts; \
    go env -w GOPRIVATE="github.com/SB-IM"; \
    go mod download; \
    go mod verify

COPY . .

RUN GOOS=linux go build -race -tags timetzdata -o sphinx ./cmd

ENV DEBUG_MQTT_CLIENT=false

VOLUME [ "/config" ]

ENTRYPOINT [ "/src/sphinx" ]
